### ISSUE TITLE
Language option in feed builder

### ISSUE THREAD

**Issue by JayInNH** [skyfeed-dev/skyfeed-me#1]
The Feed Builder works very well but it would benefit greatly from one small addition...

When building a feed around my favorite hockey team, I found that the team's nickname ("Habs") was also a common word in German (= "Have").

A way to have the Feed Builder filter for post language would be a valuable addition to the functionality.

**Comment by kw-666** [comment]
Remove Block:
Remove if **Language**  = **German**

**Comment by JayInNH** [comment]
Thank you, but it doesn't seem to work...?

![image](https://github.com/skyfeed-dev/skyfeed-me/assets/143519927/2d844d72-611e-4691-bae7-7b1107a5481f)

**Comment by kw-666** [comment]
The order of the block is very important in this case. You should try **first** set the input => network 7 days and in **second** row the filter. otherwise the filter have no impact on the input selection
i made a sample (not published) in screenshot

![Bildschirmfoto 2023-10-03 um 18 16 22](https://github.com/skyfeed-dev/skyfeed-me/assets/146489773/fb075953-6450-44b7-8e0b-cb7e1370d5b3)

**Comment by JayInNH** [comment]
Thank you. I just did as you directed, but some German posts are still getting through.

![image](https://github.com/skyfeed-dev/skyfeed-me/assets/143519927/ea1817bc-a8d9-4543-89d6-5853c8ab83b4)

**Comment by kw-666** [comment]
Hm very difficult. the feed is setup best as possible in my opinion. But "Habs" is a very generic anguage use in german.
That there are a few results left this is the best solution i think :x
Maybe the accounts have not set their language preferences correctly, post bilingually in general - or the Bluesky language filter is not 100% accurate. In the latter case, there is a good chance that it may "disappear by itself" in a future update.

to get it 100% clean, probably (for now) only helps to create a userlist and keep them out of the feed with a remove block :x they will probably never post anything about the Montreal Habs anyway ^^

**Comment by JayInNH** [comment]
I think once hashtags arrive, the whole thing will go away, but for now, my guess is that you're right about them having bilingual language settings. Thanks for your help!
